/** Tipos de notificación que el sistema puede generar hacia los usuarios. */
export enum NotificationType {
  APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED",
  APPOINTMENT_REMINDER = "APPOINTMENT_REMINDER",
  APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED",
  APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED",
  APPOINTMENT_COMPLETED = "APPOINTMENT_COMPLETED",
  REVIEW_RECEIVED = "REVIEW_RECEIVED",
  MEMBERSHIP_INVITATION = "MEMBERSHIP_INVITATION",
  PROMOTION = "PROMOTION",
}

/** Canales por los que se puede entregar una notificación. */
export enum NotificationChannel {
  IN_APP = "IN_APP",
  EMAIL = "EMAIL",
  PUSH = "PUSH",
  WHATSAPP = "WHATSAPP",
  SMS = "SMS",
}
