module.exports = {
  projects: [
    "<rootDir>/packages/shared-utils",
    "<rootDir>/packages/database",
    "<rootDir>/packages/nest-common",
    "<rootDir>/services/core-service",
    "<rootDir>/services/auth-service",
    "<rootDir>/services/booking-service",
    "<rootDir>/services/payment-service",
    "<rootDir>/services/marketplace-service",
    "<rootDir>/services/notification-service",
    "<rootDir>/services/analytics-service",
    "<rootDir>/services/api-gateway",
  ],
  preset: "ts-jest",
  transform: {
    "^.+\\.(t|j)s$": "ts-jest",
  },
  transformIgnorePatterns: ["node_modules/(?!(uuid|@nestjs|@golevelup))"],
  moduleFileExtensions: ["js", "json", "ts"],
  testEnvironment: "node",
  testRegex: ".*\\.spec\\.ts$",
  collectCoverageFrom: [
    "**/*.(t|j)s",
    "!**/*.spec.ts",
    "!**/*.dto.ts",
    "!**/*.entity.ts",
    "!**/*.interface.ts",
    "!**/main.ts",
  ],
  coverageDirectory: "coverage",
};
