module.exports = {
  rootDir: ".",
  projects: [
    "<rootDir>/packages/shared-utils",
    "<rootDir>/packages/database",
    "<rootDir>/packages/nest-common",
    "<rootDir>/packages/shared-types",
    "<rootDir>/packages/event-types",
    "<rootDir>/packages/shared-constants",
    "<rootDir>/services/core-service",
    "<rootDir>/services/auth-service",
    "<rootDir>/services/booking-service",
    "<rootDir>/services/payment-service",
    "<rootDir>/services/marketplace-service",
    "<rootDir>/services/notification-service",
    "<rootDir>/services/analytics-service",
    "<rootDir>/services/api-gateway",
  ],
  preset: "ts-jest",
  transform: {
    "^.+\\.(t|j)s$": "ts-jest",
  },
  transformIgnorePatterns: ["node_modules/(?!(uuid|@nestjs|@golevelup))"],
  moduleFileExtensions: ["js", "json", "ts"],
  moduleDirectories: ["node_modules", "packages", "services"],
  testEnvironment: "node",
  testRegex: ".*\\.spec\\.ts$",
  collectCoverageFrom: [
    "**/*.(t|j)s",
    "!**/*.spec.ts",
    "!**/*.dto.ts",
    "!**/*.entity.ts",
    "!**/*.interface.ts",
    "!**/main.ts",
  ],
  coverageDirectory: "coverage",
  moduleNameMapper: {
    "^@beautyspot/database$": "<rootDir>/packages/database/src",
    "^@beautyspot/shared-types$": "<rootDir>/packages/shared-types/src",
    "^@beautyspot/shared-utils$": "<rootDir>/packages/shared-utils/src",
    "^@beautyspot/event-types$": "<rootDir>/packages/event-types/src",
    "^@beautyspot/shared-constants$": "<rootDir>/packages/shared-constants/src",
    "^@beautyspot/nest-common$": "<rootDir>/packages/nest-common/src",
    "^@/(.*)$": "<rootDir>/$1",
  },
};
